const medDB = {
    subjects: [
        {
            id: "physio",
            title: "Фізіологія",
            en: "Physiology",
            topics: [
                {
                    id: "ps-1",
                    title: "Excitable Tissues & Muscles",
                    content: `
                        <div class="krok-marker">Core Concepts:</div>
                        <ul class="list-disc pl-5">
                            <li><strong>Depolarization:</strong> $Na^+$ influx into the cell.</li>
                            <li><strong>Repolarization:</strong> $K^+$ efflux from the cell.</li>
                            <li><strong>Absolute Refractory:</strong> $Na^+$ channels are inactivated.</li>
                            <li><strong>Ca2+ ions:</strong> Essential for actin-myosin binding.</li>
                        </ul>
                    `,
                    questions: [
                        { q: "Which ion is responsible for the depolarization phase?", options: ["$Na^+$ influx", "$K^+$ efflux", "$Ca^{2+}$ influx", "$Mg^{2+}$"], correct: 0, lang: "en" },
                        { q: "Cell excitability decreases if the stimulation threshold is:", options: ["Increased", "Decreased", "Unchanged", "Zero"], correct: 0, lang: "en" },
                        { q: "Neurotransmitter in the neuromuscular junction is:", options: ["Acetylcholine", "Epinephrine", "Dopamine", "GABA"], correct: 0, lang: "en" },
                        { q: "Blocking the $Na^+/K^+$ pump will lead to:", options: ["Loss of resting potential", "Hyperpolarization", "Increased excitability", "No effect"], correct: 0, lang: "en" },
                        { q: "Which protein binds with $Ca^{2+}$ to initiate contraction?", options: ["Troponin C", "Tropomyosin", "Actin", "Myosin"], correct: 0, lang: "en" },
                        { q: "Isometric contraction means:", options: ["Tension changes, length remains", "Length changes, tension remains", "Both change", "Neither changes"], correct: 0, lang: "en" },
                        { q: "Saltatory conduction occurs in:", options: ["Myelinated fibers", "Unmyelinated fibers", "Muscle fibers", "Dendrites"], correct: 0, lang: "en" },
                        { q: "The 'all-or-none' law primarily applies to:", options: ["Single muscle fiber", "Whole muscle", "Whole nerve", "Glandular tissue"], correct: 0, lang: "en" },
                        { q: "Velocity of impulse is proportional to:", options: ["Fiber diameter", "Fiber length", "Stimulus strength", "Temperature"], correct: 0, lang: "en" },
                        { q: "Which ion's intracellular concentration is the lowest?", options: ["$Ca^{2+}$", "$K^+$", "$Na^+$", "$Mg^{2+}$"], correct: 0, lang: "en" },
                        { q: "Inhibitory neurotransmitter in the spinal cord is:", options: ["Glycine", "Glutamate", "Acetylcholine", "Noradrenaline"], correct: 0, lang: "en" },
                        { q: "Acetylcholinesterase inhibition leads to:", options: ["Prolonged contraction", "Muscle paralysis", "Immediate relaxation", "ACh deficiency"], correct: 0, lang: "en" },
                        { q: "Complete tetanus occurs when frequency hits:", options: ["Contraction phase", "Relaxation phase", "Rest phase", "Refractory period"], correct: 0, lang: "en" },
                        { q: "The primary cause of resting potential is:", options: ["$K^+$ efflux", "$Na^+$ influx", "$Cl^-$ influx", "Active $Ca^{2+}$ transport"], correct: 0, lang: "en" },
                        { q: "Phase of plateau in cardiomyocytes is caused by:", options: ["$Ca^{2+}$ influx", "$Na^+$ efflux", "$K^+$ influx", "$Cl^-$ efflux"], correct: 0, lang: "en" },
                        { q: "Minimal strength of a stimulus is called:", options: ["Threshold", "Rheobase", "Chronaxy", "Summation"], correct: 0, lang: "en" },
                        { q: "Curare-like drugs block which receptors?", options: ["N-cholinergic", "M-cholinergic", "Alpha-adrenergic", "Beta-adrenergic"], correct: 0, lang: "en" },
                        { q: "Initial length of fiber determines force in:", options: ["Frank-Starling law", "Bowditch law", "Bell-Magendie law", "All-or-none"], correct: 0, lang: "en" },
                        { q: "Energy for $Na^+/K^+$ pump is provided by:", options: ["ATP hydrolysis", "Glucose diffusion", "Gradient energy", "Oxygen"], correct: 0, lang: "en" },
                        { q: "H-zone in a sarcomere contains only:", options: ["Myosin", "Actin", "Troponin", "Z-disks"], correct: 0, lang: "en" },
                        { q: "Synaptic delay is primarily caused by:", options: ["Mediator release and diffusion", "Axon conduction", "Receptor synthesis", "$Na^+$ channels"], correct: 0, lang: "en" },
                        { q: "Dantrolene blocks $Ca^{2+}$ release from:", options: ["Sarcoplasmic reticulum", "Mitochondria", "Extracellular space", "Nucleus"], correct: 0, lang: "en" },
                        { q: "Which ion maintains the plateau in the heart?", options: ["$Ca^{2+}$", "$Na^+$", "$K^+$", "$Cl^-$"], correct: 0, lang: "en" },
                        { q: "Post-tetanic potentiation is due to:", options: ["Residual $Ca^{2+}$", "ACh exhaustion", "Loss of $K^+$", "Na+ channel block"], correct: 0, lang: "en" },
                        { q: "Hyperpolarization is caused by:", options: ["Increased $K^+$ conductance", "$Na^+$ entry", "Blocked Cl- channels", "$Ca^{2+}$ entry"], correct: 0, lang: "en" },
                        { q: "The main source of $Ca^{2+}$ for smooth muscle is:", options: ["Extracellular fluid", "Sarcoplasmic reticulum", "Mitochondria", "Lysosomes"], correct: 0, lang: "en" },
                        { q: "Rigor mortis occurs due to lack of:", options: ["ATP", "$Ca^{2+}$", "ACh", "Myosin"], correct: 0, lang: "en" },
                        { q: "Excitatory postsynaptic potential (EPSP) is caused by:", options: ["$Na^+$ influx", "$K^+$ efflux", "$Cl^-$ influx", "Hyperpolarization"], correct: 0, lang: "en" },
                        { q: "Temporal summation involves:", options: ["Repeated stimuli from one source", "Multiple sources", "Constant stimulus", "Inhibition"], correct: 0, lang: "en" },
                        { q: "Spatial summation involves:", options: ["Multiple sources", "One repeated source", "Long duration", "Fatigue"], correct: 0, lang: "en" }
                    ]
                },
                {
                    id: "ps-2",
                    title: "Blood Physiology (Hematology)",
                    content: `<div class="krok-marker">Norms: CI 0.85-1.05. pH 7.35-7.45. Group I(0) = No antigens.</div>`,
                    questions: [
                        { q: "Color index 0.7 indicates:", options: ["Hypochromic anemia", "Hyperchromic", "Normal", "B12 deficiency"], correct: 0, lang: "en" },
                        { q: "No agglutinins in plasma means blood group:", options: ["IV(AB)", "I(0)", "II(A)", "III(B)"], correct: 0, lang: "en" },
                        { q: "Vitamin K is essential for:", options: ["Clotting factors", "RBC production", "Iron absorption", "WBC function"], correct: 0, lang: "en" },
                        { q: "Oncotic pressure is maintained by:", options: ["Albumins", "Globulins", "NaCl", "Glucose"], correct: 0, lang: "en" },
                        { q: "Erythropoietin is mainly produced in:", options: ["Kidneys", "Liver", "Spleen", "Bone marrow"], correct: 0, lang: "en" },
                        { q: "Universal donor group (by RBCs) is:", options: ["I(0) Rh-", "IV(AB) Rh+", "II(A) Rh-", "III(B) Rh+"], correct: 0, lang: "en" },
                        { q: "Shift to the left in WBC formula means increase of:", options: ["Band neutrophils", "Lymphocytes", "Monocytes", "Eosinophils"], correct: 0, lang: "en" },
                        { q: "Normal blood pH is:", options: ["7.35 - 7.45", "7.00 - 7.10", "6.80 - 7.00", "7.60 - 7.80"], correct: 0, lang: "en" },
                        { q: "Heparin's primary role is:", options: ["Anticoagulant", "Coagulant", "Erythropoiesis", "Immunity"], correct: 0, lang: "en" },
                        { q: "B12 deficiency leads to:", options: ["Megaloblastic anemia", "Microcytic", "Hemolytic", "Aplastic"], correct: 0, lang: "en" },
                        { q: "Platelet count below 150,000/µL is:", options: ["Thrombocytopenia", "Thrombocytosis", "Leukopenia", "Anemia"], correct: 0, lang: "en" },
                        { q: "Main cation of extracellular fluid is:", options: ["$Na^+$", "$K^+$", "$Ca^{2+}$", "$Mg^{2+}$"], correct: 0, lang: "en" },
                        { q: "Main cation of intracellular fluid is:", options: ["$K^+$", "$Na^+$", "$Ca^{2+}$", "$Mg^{2+}$"], correct: 0, lang: "en" },
                        { q: "Fibrinogen is converted to fibrin by:", options: ["Thrombin", "Prothrombin", "Heparin", "Vitamin K"], correct: 0, lang: "en" },
                        { q: "Which cell produces antibodies?", options: ["Plasma cell (B-lymphocyte)", "T-lymphocyte", "Macrophage", "Eosinophil"], correct: 0, lang: "en" },
                        { q: "Hematocrit represents:", options: ["RBC volume %", "WBC count", "Plasma volume", "Hb level"], correct: 0, lang: "en" },
                        { q: "Iron is transported in blood by:", options: ["Transferrin", "Ferritin", "Hemoglobin", "Albumin"], correct: 0, lang: "en" },
                        { q: "Iron is stored in the liver as:", options: ["Ferritin", "Transferrin", "Hemoglobin", "Bilirubin"], correct: 0, lang: "en" },
                        { q: "Eosinophilia is most typical for:", options: ["Parasitic infections", "Bacterial infection", "Heart failure", "Diabetes"], correct: 0, lang: "en" },
                        { q: "Life span of an average erythrocyte is:", options: ["120 days", "30 days", "1 year", "10 days"], correct: 0, lang: "en" },
                        { q: "Blood group II(A) has which antigens?", options: ["Antigen A", "Antigen B", "Both", "None"], correct: 0, lang: "en" },
                        { q: "Agglutinin 'alpha' is found in:", options: ["Groups I and III", "Groups II and IV", "Only Group I", "Only Group III"], correct: 0, lang: "en" },
                        { q: "Serum differs from plasma by absence of:", options: ["Fibrinogen", "Albumin", "Glucose", "$Na^+$"], correct: 0, lang: "en" },
                        { q: "Hemolysis in 0.3% NaCl is:", options: ["Normal", "Pathological", "Impossible", "Instant"], correct: 0, lang: "en" },
                        { q: "Neutrophils primarily perform:", options: ["Phagocytosis", "Antibody production", "O2 transport", "Clotting"], correct: 0, lang: "en" },
                        { q: "Which buffer is the most powerful?", options: ["Hemoglobin", "Bicarbonate", "Phosphate", "Protein"], correct: 0, lang: "en" },
                        { q: "Bilirubin is a product of:", options: ["Hemoglobin breakdown", "Protein synthesis", "Bile production", "Glucose metabolism"], correct: 0, lang: "en" },
                        { q: "Main function of albumin is:", options: ["Oncotic pressure", "O2 transport", "Blood clotting", "Hormone synthesis"], correct: 0, lang: "en" },
                        { q: "Clot retraction is mediated by:", options: ["Platelets", "RBCs", "WBCs", "Plasma"], correct: 0, lang: "en" },
                        { q: "Plasmin is responsible for:", options: ["Fibrinolysis", "Clotting", "Erythropoiesis", "Leukopoiesis"], correct: 0, lang: "en" }
                    ]
                },
                {
                    id: "ps-3",
                    title: "Cardiovascular System (CVS)",
                    content: `<div class="krok-marker">ECG: P-atria, QRS-ventricles. Vagus: Bradycardia. S1: AV valves close.</div>`,
                    questions: [
                        { q: "P wave absent means pacemaker is in:", options: ["AV node", "SA node", "His bundle", "Purkinje"], correct: 0, lang: "en" },
                        { q: "ECG wave for ventricular repolarization is:", options: ["T wave", "P wave", "QRS", "U wave"], correct: 0, lang: "en" },
                        { q: "Vagus nerve stimulation causes:", options: ["Bradycardia", "Tachycardia", "Increased BP", "No change"], correct: 0, lang: "en" },
                        { q: "BP 160/100. Pulse pressure is:", options: ["60 mmHg", "160", "100", "260"], correct: 0, lang: "en" },
                        { q: "First heart sound (S1) reflects:", options: ["AV valves closure", "Semilunar closure", "Atrial systole", "Aortic opening"], correct: 0, lang: "en" },
                        { q: "Slowest conduction in the heart is in:", options: ["AV node", "Purkinje", "Atria", "Ventricles"], correct: 0, lang: "en" },
                        { q: "Fastest conduction in the heart is in:", options: ["Purkinje fibers", "AV node", "Atria", "Ventricles"], correct: 0, lang: "en" },
                        { q: "Frank-Starling law links force to:", options: ["Initial length", "Heart rate", "pH", "Oxygen"], correct: 0, lang: "en" },
                        { q: "Second heart sound (S2) reflects:", options: ["Semilunar closure", "AV closure", "Atrial systole", "Ventricular filling"], correct: 0, lang: "en" },
                        { q: "Normal heart rate is set by:", options: ["Sinoatrial node", "AV node", "His bundle", "Vagus"], correct: 0, lang: "en" },
                        { q: "Atropine causes:", options: ["Tachycardia", "Bradycardia", "Miosis", "Sweating"], correct: 0, lang: "en" },
                        { q: "Total peripheral resistance is highest in:", options: ["Arterioles", "Aorta", "Capillaries", "Veins"], correct: 0, lang: "en" },
                        { q: "Blood flow is slowest in:", options: ["Capillaries", "Aorta", "Arterioles", "Vena cava"], correct: 0, lang: "en" },
                        { q: "Which wave shows atrial depolarization?", options: ["P wave", "QRS", "T wave", "P-Q"], correct: 0, lang: "en" },
                        { q: "Cardiac output is:", options: ["HR x Stroke Volume", "BP / Resistance", "HR + SV", "Pulse pressure x 2"], correct: 0, lang: "en" },
                        { q: "Isovolumetric contraction phase means:", options: ["All valves closed", "AV open", "Semilunar open", "Atria contract"], correct: 0, lang: "en" },
                        { q: "Parasympathetic effect on heart is mediated by:", options: ["Acetylcholine", "Noradrenaline", "Adrenaline", "Dopamine"], correct: 0, lang: "en" },
                        { q: "Sympathetic effect on heart is mediated by:", options: ["Noradrenaline", "Acetylcholine", "GABA", "Serotonin"], correct: 0, lang: "en" },
                        { q: "Baroreceptors are located in:", options: ["Aortic arch/Carotid sinus", "Left ventricle", "Lungs", "Brain"], correct: 0, lang: "en" },
                        { q: "Which ion causes the pacemaker potential?", options: ["$Na^+$ leakage", "$K^+$ exit", "$Ca^{2+}$ block", "$Cl^-$ entry"], correct: 0, lang: "en" },
                        { q: "Venous return is primarily aided by:", options: ["Skeletal muscle pump", "Atrial suction", "Gravity", "Arterial pressure"], correct: 0, lang: "en" },
                        { q: "Ejection fraction is:", options: ["SV / End-diastolic volume", "SV x HR", "BP / Resistance", "Normal if 30%"], correct: 0, lang: "en" },
                        { q: "A-V interval delay is for:", options: ["Ventricular filling", "Atrial filling", "Coronary flow", "Nerve rest"], correct: 0, lang: "en" },
                        { q: "Systolic pressure reflects:", options: ["Left ventricle work", "Vessel elasticity", "Venous return", "Lung pressure"], correct: 0, lang: "en" },
                        { q: "Diastolic pressure reflects:", options: ["Peripheral resistance", "Max heart force", "Atrial work", "Blood volume only"], correct: 0, lang: "en" },
                        { q: "Anrep effect is:", options: ["Autoregulation by pressure", "Starling's law", "Vagus effect", "Sympathetic effect"], correct: 0, lang: "en" },
                        { q: "Bainbridge reflex is:", options: ["HR increase due to atrium stretch", "HR decrease", "BP drop", "Apnea"], correct: 0, lang: "en" },
                        { q: "Third heart sound is:", options: ["Rapid ventricular filling", "Atrial contraction", "AV closure", "Aortic closure"], correct: 0, lang: "en" },
                        { q: "QRS duration normally is:", options: ["0.06-0.10s", "0.20s", "0.50s", "0.01s"], correct: 0, lang: "en" },
                        { q: "Myocardial absolute refractory period is:", options: ["Long", "Short", "Absent", "Same as skeletal"], correct: 0, lang: "en" }
                    ]
                },
                {
                    id: "ps-4",
                    title: "Respiration & Digestion",
                    content: `<div class="krok-marker">Surfactant prevents collapse. Trypsinogen + Enterokinase = Trypsin. Bile = Fats.</div>`,
                    questions: [
                        { q: "Surfactant prevents:", options: ["Alveolar collapse", "Edema", "Infection", "Cough"], correct: 0, lang: "en" },
                        { q: "VC = TV + IRV + ERV. True?", options: ["Yes", "No", "Only for men", "Only for athletes"], correct: 0, lang: "en" },
                        { q: "Trypsinogen is activated by:", options: ["Enterokinase", "Bile", "HCl", "Pepsin"], correct: 0, lang: "en" },
                        { q: "Bile is required for:", options: ["Fat emulsification", "Protein digestion", "Starch breakdown", "Sugar transport"], correct: 0, lang: "en" },
                        { q: "Hering-Breuer reflex prevents:", options: ["Lung overinflation", "Apnea", "Cough", "Hypercapnia"], correct: 0, lang: "en" },
                        { q: "Main $CO_2$ transport form is:", options: ["Bicarbonates ($HCO_3^-$)", "Dissolved", "Carbamino-Hb", "Gas bubbles"], correct: 0, lang: "en" },
                        { q: "Respiratory center is most sensitive to:", options: ["$CO_2$", "$O_2$", "Nitrogen", "pH only"], correct: 0, lang: "en" },
                        { q: "Parietal cells secrete:", options: ["HCl and Intrinsic factor", "Pepsinogen", "Gastrin", "Mucus"], correct: 0, lang: "en" },
                        { q: "Chief cells secrete:", options: ["Pepsinogen", "HCl", "Gastrin", "Mucus"], correct: 0, lang: "en" },
                        { q: "Salivary amylase starts digestion of:", options: ["Carbohydrates", "Proteins", "Fats", "Vitamins"], correct: 0, lang: "en" },
                        { q: "Hormone stimulating HCl is:", options: ["Gastrin", "Secretin", "CCK", "Insulin"], correct: 0, lang: "en" },
                        { q: "Hormone stimulating bile ejection is:", options: ["CCK (Cholecystokinin)", "Gastrin", "Secretin", "Glucagon"], correct: 0, lang: "en" },
                        { q: "Residual volume is air left after:", options: ["Maximal expiration", "Normal expiration", "Inspiration", "Eating"], correct: 0, lang: "en" },
                        { q: "Dead space air does not participate in:", options: ["Gas exchange", "Humidification", "Warming", "Filtration"], correct: 0, lang: "en" },
                        { q: "Partial pressure of $O_2$ in arterial blood is:", options: ["100 mmHg", "40 mmHg", "160 mmHg", "46 mmHg"], correct: 0, lang: "en" },
                        { q: "Partial pressure of $O_2$ in venous blood is:", options: ["40 mmHg", "100 mmHg", "46 mmHg", "0 mmHg"], correct: 0, lang: "en" },
                        { q: "Oxygen binds to which part of Hb?", options: ["Iron ($Fe^{2+}$) in Heme", "Globin chain", "Alpha chain", "Plasma"], correct: 0, lang: "en" },
                        { q: "Intrapleural pressure is:", options: ["Negative (sub-atmospheric)", "Positive", "Zero", "Changing to +10"], correct: 0, lang: "en" },
                        { q: "Peripheral chemoreceptors are in:", options: ["Carotid/Aortic bodies", "Medulla", "Lungs", "Skin"], correct: 0, lang: "en" },
                        { q: "Central chemoreceptors sense:", options: ["$H^+$ in CSF (via $CO_2$)", "$O_2$ drop", "Glucose", "Pressure"], correct: 0, lang: "en" },
                        { q: "Pneumothorax leads to:", options: ["Lung collapse", "Hyperventilation", "Better exchange", "No change"], correct: 0, lang: "en" },
                        { q: "Secretin stimulates:", options: ["Pancreatic bicarbonate", "Pancreatic enzymes", "Gastrin", "Saliva"], correct: 0, lang: "en" },
                        { q: "Intrinsic factor is needed for:", options: ["B12 absorption", "Iron absorption", "Fat digestion", "HCl production"], correct: 0, lang: "en" },
                        { q: "Steatorrhea (fat in stool) is due to lack of:", options: ["Bile/Lipase", "Pepsin", "Amylase", "Insulin"], correct: 0, lang: "en" },
                        { q: "Primary site of nutrient absorption is:", options: ["Small intestine", "Stomach", "Large intestine", "Esophagus"], correct: 0, lang: "en" },
                        { q: "Function of the large intestine is:", options: ["Water reabsorption", "Protein digestion", "Fat digestion", "Acid production"], correct: 0, lang: "en" },
                        { q: "Villi increase the:", options: ["Absorption surface", "Speed of food", "HCl production", "Acid protection"], correct: 0, lang: "en" },
                        { q: "Chyme is:", options: ["Semi-liquid food mass", "Saliva", "Stool", "Enzyme"], correct: 0, lang: "en" },
                        { q: "Defecation center is in:", options: ["Sacral spinal cord", "Medulla", "Hypothalamus", "Frontal lobe"], correct: 0, lang: "en" },
                        { q: "Enterogastric reflex:", options: ["Inhibits stomach motility", "Speeds up stomach", "Triggers hunger", "Stops thirst"], correct: 0, lang: "en" }
                    ]
                },
                {
                    id: "ps-5",
                    title: "Excretion, Endocrine & CNS",
                    content: `<div class="krok-marker">GFR 125ml/min. Insulin lowers sugar. Acromegaly = adult GH excess.</div>`,
                    questions: [
                        { q: "Glucose reabsorption occurs in:", options: ["Proximal tubules", "Distal", "Loop of Henle", "Collecting"], correct: 0, lang: "en" },
                        { q: "Filtration stops if BP is:", options: ["< 70 mmHg", "120", "90", "150"], correct: 0, lang: "en" },
                        { q: "Vasopressin (ADH) increases:", options: ["Water reabsorption", "$Na^+$ reabsorption", "Glucose reabsorption", "Filtration"], correct: 0, lang: "en" },
                        { q: "Aldosterone increases:", options: ["$Na^+$ reabsorption", "Water excretion", "Glucose excretion", "$K^+$ reabsorption"], correct: 0, lang: "en" },
                        { q: "Acromegaly in adults is due to:", options: ["GH excess", "Thyroxine excess", "Insulin lack", "Cortisol excess"], correct: 0, lang: "en" },
                        { q: "Insulin's main role is to:", options: ["Lower blood glucose", "Raise glucose", "Raise calcium", "Lower BP"], correct: 0, lang: "en" },
                        { q: "Diabetes insipidus is lack of:", options: ["ADH (Vasopressin)", "Insulin", "Aldosterone", "Thyroxine"], correct: 0, lang: "en" },
                        { q: "Weight loss + Exophthalmos + Tachycardia:", options: ["Hyperthyroidism", "Hypothyroidism", "Diabetes", "Addison's"], correct: 0, lang: "en" },
                        { q: "Sanguine type is:", options: ["Strong, balanced, mobile", "Unbalanced", "Weak", "Inert"], correct: 0, lang: "en" },
                        { q: "Cerebellum damage causes:", options: ["Ataxia/Coordination loss", "Vision loss", "Deafness", "Memory loss"], correct: 0, lang: "en" },
                        { q: "Glomerular Filtration Rate (GFR) is:", options: ["125 ml/min", "500 ml/min", "10 ml/min", "1 L/min"], correct: 0, lang: "en" },
                        { q: "Inulin clearance measures:", options: ["GFR", "Renal blood flow", "Tubular secretion", "Glucose reabsorption"], correct: 0, lang: "en" },
                        { q: "Renin is released by:", options: ["Juxtaglomerular cells", "Liver", "Lungs", "Heart"], correct: 0, lang: "en" },
                        { q: "Normal urine should not contain:", options: ["Glucose and Protein", "Urea", "Creatinine", "$Na^+$"], correct: 0, lang: "en" },
                        { q: "Specific gravity of urine depends on:", options: ["Dissolved solutes", "Water only", "Color", "pH"], correct: 0, lang: "en" },
                        { q: "Parathyroid hormone (PTH) raises:", options: ["Blood Calcium", "Blood Sodium", "Blood Glucose", "Blood $K^+$"], correct: 0, lang: "en" },
                        { q: "Calcitonin lowers:", options: ["Blood Calcium", "Blood Sodium", "Blood Glucose", "Blood $K^+$"], correct: 0, lang: "en" },
                        { q: "Cushing's syndrome is excess of:", options: ["Glucocorticoids (Cortisol)", "Thyroxine", "Insulin", "Growth hormone"], correct: 0, lang: "en" },
                        { q: "Addison's disease is lack of:", options: ["Adrenal cortex hormones", "Insulin", "PTH", "ADH"], correct: 0, lang: "en" },
                        { q: "Which hormone is the 'fight-or-flight'?", options: ["Adrenaline (Epinephrine)", "Insulin", "Melatonin", "Prolactin"], correct: 0, lang: "en" },
                        { q: "Oxytocin is responsible for:", options: ["Uterine contraction/Milk letdown", "Milk production", "Sperm production", "Water retention"], correct: 0, lang: "en" },
                        { q: "Prolactin is responsible for:", options: ["Milk production", "Milk ejection", "Thirst", "Sleep"], correct: 0, lang: "en" },
                        { q: "Pineal gland produces:", options: ["Melatonin", "Thyroxine", "Insulin", "Dopamine"], correct: 0, lang: "en" },
                        { q: "Wernicke's area is for:", options: ["Speech understanding", "Speech production", "Vision", "Hearing tone"], correct: 0, lang: "en" },
                        { q: "Broca's area is for:", options: ["Motor speech production", "Understanding", "Vision", "Balance"], correct: 0, lang: "en" },
                        { q: "Occipital lobe is for:", options: ["Vision", "Hearing", "Smell", "Motor skills"], correct: 0, lang: "en" },
                        { q: "Temporal lobe is for:", options: ["Hearing/Memory", "Vision", "Pain", "Motor skills"], correct: 0, lang: "en" },
                        { q: "Babinski sign in adults shows:", options: ["Pyramidal tract damage", "Normal reflex", "Cerebellum damage", "Thalamus damage"], correct: 0, lang: "en" },
                        { q: "Hypothalamus controls:", options: ["Homeostasis/Thermoregulation", "Coordination", "Vision", "Voluntary movement"], correct: 0, lang: "en" },
                        { q: "Alpha-blockers would cause:", options: ["Vasodilation", "Vasoconstriction", "Tachycardia", "Pupil dilation"], correct: 0, lang: "en" }
                    ]
                }
            ]
        },
        { id: "pharma", title: "Фармакологія", en: "Pharmacology", topics: [] },
        { id: "pathmorph", title: "Патоморфологія", en: "Pathomorphology", topics: [] },
        { id: "pathphys", title: "Патофізіологія", en: "Pathophysiology", topics: [] },
        { id: "anatomy", title: "Анатомія", en: "Anatomy", topics: [] },
        { id: "histo", title: "Гістологія", en: "Histology", topics: [] }
    ]
};
