const medDB = {
    subjects: [
        {
            id: "physio",
            title: "Фізіологія",
            en: "Physiology",
            topics: [
                {
                    id: "ps-1",
                    title: "Excitable Tissues & Nerve-Muscle Physiology",
                    content: `<div class="krok-marker">Focus:</div><p>Action potentials, $Na^+/K^+$ pumps, and neurotransmitters in clinical scenarios.</p>`,
                    questions: [
                        { q: "A patient with myasthenia gravis is treated with a drug that inhibits acetylcholinesterase. Which ionic process will be prolonged?", options: ["$Na^+$ influx", "$K^+$ efflux", "$Ca^{2+}$ influx", "$Cl^-$ influx"], correct: 0, lang: "en" },
                        { q: "A 45-year-old male exhibits muscle spasms after accidental removal of the parathyroid glands. Deficiency of which ion causes this?", options: ["$Ca^{2+}$", "$Na^+$", "$K^+$", "$Mg^{2+}$"], correct: 0, lang: "en" },
                        { q: "An experimental study shows a neuron has a resting potential of -70 mV. If extracellular $K^+$ is increased, what happens?", options: ["Depolarization", "Hyperpolarization", "No change", "Action potential generation"], correct: 0, lang: "en" },
                        { q: "A muscle relaxant that blocks N-cholinergic receptors was administered. What is its primary mechanism?", options: ["Blocking synaptic transmission", "Inhibiting ACh release", "Inactivating $Na^+$ channels", "Activating $K^+$ channels"], correct: 0, lang: "en" },
                        { q: "Stimulus strength is exactly at the threshold. How will the fiber respond if the duration is halved?", options: ["No response (Subthreshold)", "Normal action potential", "Increased action potential", "Hyperpolarization"], correct: 0, lang: "en" },
                        { q: "A muscle produces a smooth tetanic contraction. This happens when each subsequent stimulus falls into which period?", options: ["Contraction phase", "Relaxation phase", "Absolute refractory period", "Latent period"], correct: 0, lang: "en" },
                        { q: "Botulism poisoning leads to respiratory failure. What is the mechanism of the toxin at the junction?", options: ["Inhibition of Acetylcholine release", "Blocking N-receptors", "Inactivation of $Ca^{2+}$ channels", "Inhibition of Cholinesterase"], correct: 0, lang: "en" },
                        { q: "Curare-like drugs induce muscle relaxation by competing with acetylcholine for which specific structure?", options: ["N-cholinergic receptors", "M-cholinergic receptors", "Acetylcholinesterase", "$Na^+$ channels"], correct: 0, lang: "en" },
                        { q: "Tetrodotoxin blocks $Na^+$ channels of a nerve fiber. Which process will be primarily inhibited?", options: ["Depolarization", "Repolarization", "Resting potential maintenance", "Active transport of $K^+$"], correct: 0, lang: "en" },
                        { q: "A nerve fiber lost its myelin sheath due to injury. How does the conduction of the impulse change?", options: ["Continuous and slower", "Saltatory and faster", "Saltatory but slower", "Completely blocked"], correct: 0, lang: "en" },
                        { q: "A patient is diagnosed with hypokalemia. How will this state primarily affect the resting membrane potential?", options: ["Hyperpolarization", "Depolarization", "No effect", "Action potential onset"], correct: 0, lang: "en" },
                        { q: "A drug increases the threshold of stimulation for a nerve fiber. How does the excitability change?", options: ["Decreases", "Increases", "Remains constant", "Disappears"], correct: 0, lang: "en" },
                        { q: "Which ion movement into the nerve terminal triggers the release of neurotransmitters into the cleft?", options: ["$Ca^{2+}$ influx", "$Na^+$ influx", "$K^+$ efflux", "$Cl^-$ influx"], correct: 0, lang: "en" },
                        { q: "Dantrolene prevents $Ca^{2+}$ release from the sarcoplasmic reticulum. Which process is directly blocked?", options: ["Electromechanical coupling", "Action potential conduction", "ACh binding", "$Na^+$ transport"], correct: 0, lang: "en" },
                        { q: "A technician blocks the $Na^+/K^+$ pump. What will be the most immediate result in the cell?", options: ["Gradual loss of resting potential", "Immediate hyperpolarization", "Increase in conduction speed", "Decrease in cell volume"], correct: 0, lang: "en" },
                        // (Усього в цьому розділі 30 кейсів)
                        { q: "The absolute refractory period is caused by the inactivation of which channels?", options: ["Voltage-gated $Na^+$ channels", "$K^+$ channels", "$Ca^{2+}$ channels", "Anion channels"], correct: 0, lang: "en" },
                        { q: "Which protein binds $Ca^{2+}$ to initiate skeletal muscle contraction?", options: ["Troponin C", "Tropomyosin", "Actin", "Myosin"], correct: 0, lang: "en" },
                        { q: "A person touched a hot wire; the muscle stays contracted. Which ion remains high in the sarcoplasm?", options: ["$Ca^{2+}$", "$Na^+$", "$K^+$", "$Mg^{2+}$"], correct: 0, lang: "en" },
                        { q: "Local anesthetics like Lidocaine block conduction by inhibiting:", options: ["Voltage-gated $Na^+$ channels", "M-cholinergic receptors", "$K^+$ channels", "ATP synthesis"], correct: 0, lang: "en" },
                        { q: "The law of 'all-or-none' means that a single fiber responds to a threshold stimulus by:", options: ["Maximum possible contraction", "Partial contraction", "Local potential only", "Hyperpolarization"], correct: 0, lang: "en" },
                        { q: "A person is in a state of 'rigor mortis'. This is caused by a lack of:", options: ["ATP", "$Ca^{2+}$", "Glycogen", "Acetylcholine"], correct: 0, lang: "en" },
                        { q: "What is the primary inhibitory neurotransmitter in the spinal cord?", options: ["Glycine", "Glutamate", "Acetylcholine", "Dopamine"], correct: 0, lang: "en" },
                        { q: "Which ionic current causes the rapid repolarization phase of an action potential?", options: ["$K^+$ efflux", "$Na^+$ influx", "$Ca^{2+}$ influx", "$Cl^-$ influx"], correct: 0, lang: "en" },
                        { q: "Increasing the diameter of a nerve fiber has what effect on conduction velocity?", options: ["Increases velocity", "Decreases velocity", "No effect", "Blocks conduction"], correct: 0, lang: "en" },
                        { q: "Which neurotransmitter is used by preganglionic autonomic fibers?", options: ["Acetylcholine", "Norepinephrine", "Serotonin", "GABA"], correct: 0, lang: "en" },
                        { q: "Complete tetanus occurs when each subsequent stimulus hits which period?", options: ["Contraction phase", "Relaxation phase", "Refractory period", "Latent phase"], correct: 0, lang: "en" },
                        { q: "The poison strychnine blocks glycine receptors. This leads to:", options: ["Uncontrolled muscle spasms", "Flaccid paralysis", "Loss of sensation", "Sleepiness"], correct: 0, lang: "en" },
                        { q: "Saltatory conduction is found in which types of fibers?", options: ["Myelinated", "Unmyelinated", "Skeletal muscle", "Smooth muscle"], correct: 0, lang: "en" },
                        { q: "The N-cholinergic receptor is what type of receptor?", options: ["Ionotropic", "Metabotropic", "Nuclear", "Enzymatic"], correct: 0, lang: "en" },
                        { q: "What happens to the sarcomere during contraction?", options: ["Distance between Z-lines decreases", "A-band disappears", "I-band widens", "Myosin filaments shorten"], correct: 0, lang: "en" }
                    ]
                },
                {
                    id: "ps-2",
                    title: "Blood & Body Fluids (Hematology)",
                    content: `<div class="krok-marker">Focus:</div><p>Anemia types, blood groups, pH, and osmotic resistance.</p>`,
                    questions: [
                        { q: "A 25-year-old pregnant woman has Hb 90 g/L, RBC $3.0 \\times 10^{12}/L$, and CI 0.7. Most likely diagnosis?", options: ["Iron-deficiency anemia", "Vitamin $B_{12}$ deficiency", "Hemolytic anemia", "Aplastic anemia"], correct: 0, lang: "en" },
                        { q: "A victim of a car accident needs a transfusion. Group is II(A) Rh-. If not available, which one to choose?", options: ["I(0) Rh-", "II(A) Rh+", "III(B) Rh-", "IV(AB) Rh-"], correct: 0, lang: "en" },
                        { q: "Chronic kidney disease patient has severe anemia. Deficiency of which hormone is the cause?", options: ["Erythropoietin", "Renin", "Vasopressin", "Aldosterone"], correct: 0, lang: "en" },
                        { q: "Severe allergic reaction shows an increase in which leukocyte type?", options: ["Eosinophils", "Basophils", "Monocytes", "Neutrophils"], correct: 0, lang: "en" },
                        { q: "Newborn develops jaundice due to Rh-incompatibility. Status of mother and fetus?", options: ["Mother Rh-, Fetus Rh+", "Mother Rh+, Fetus Rh-", "Both Rh-", "Both Rh+"], correct: 0, lang: "en" },
                        { q: "A total gastrectomy patient 2 years later has Hb 80 g/L and CI 1.3. Cause?", options: ["Intrinsic factor (Castle's factor)", "HCl lack", "Pepsin lack", "Bile lack"], correct: 0, lang: "en" },
                        { q: "Warfarin inhibits the action of which vitamin?", options: ["Vitamin K", "Vitamin A", "Vitamin C", "Vitamin $B_{12}$"], correct: 0, lang: "en" },
                        { q: "RBCs hemolyze in 0.48% NaCl and fully in 0.32%. This indicates decreased:", options: ["Osmotic resistance", "Oncotic pressure", "ESR", "Hematocrit"], correct: 0, lang: "en" },
                        { q: "Which plasma component maintains oncotic pressure and prevents edema?", options: ["Albumins", "Globulins", "Fibrinogen", "Glucose"], correct: 0, lang: "en" },
                        { q: "Living at 5000m for months shows increased RBC. This is triggered by:", options: ["Hypoxia stimulating erythropoietin", "Cold", "UV", "CO2"], correct: 0, lang: "en" },
                        { q: "A patient with liver cirrhosis has developed edema. A decrease in which protein is responsible?", options: ["Albumins", "Globulins", "Fibrinogen", "Prothrombin"], correct: 0, lang: "en" },
                        { q: "A person's blood group test: agglutination with Anti-A and Anti-B. Group is:", options: ["IV(AB)", "I(0)", "II(A)", "III(B)"], correct: 0, lang: "en" },
                        { q: "Blood test shows ESR of 45 mm/h. Which state is most likely?", options: ["Inflammation", "Normal", "Polycythemia", "Dehydration"], correct: 0, lang: "en" },
                        { q: "Hematocrit of 30% indicates:", options: ["Anemia", "Polycythemia", "Normal", "Leukocytosis"], correct: 0, lang: "en" },
                        { q: "What is the primary buffer system of the blood?", options: ["Bicarbonate", "Phosphate", "Protein", "Hemoglobin"], correct: 0, lang: "en" },
                        { q: "Blood pH of 7.25 and high $CO_2$ is defined as:", options: ["Respiratory acidosis", "Metabolic alkalosis", "Respiratory alkalosis", "Metabolic acidosis"], correct: 0, lang: "en" },
                        { q: "Which cell is responsible for cellular immunity?", options: ["T-lymphocytes", "B-lymphocytes", "Monocytes", "Eosinophils"], correct: 0, lang: "en" },
                        { q: "Vitamin $B_{12}$ absorption requires which substance from the stomach?", options: ["Intrinsic factor", "HCl", "Gastrin", "Pepsin"], correct: 0, lang: "en" },
                        { q: "A child has frequent parasitic infections. Which cell count will be elevated?", options: ["Eosinophils", "Neutrophils", "Basophils", "Lymphocytes"], correct: 0, lang: "en" },
                        { q: "Main function of platelets is:", options: ["Hemostasis (Clotting)", "O2 transport", "Antibody production", "Phagocytosis"], correct: 0, lang: "en" },
                        { q: "Shift to the left in leukocyte formula means an increase in:", options: ["Band neutrophils", "Monocytes", "Eosinophils", "Lymphocytes"], correct: 0, lang: "en" },
                        { q: "Which vitamin is synthesized by intestinal flora and helps clotting?", options: ["Vitamin K", "Vitamin A", "Vitamin D", "Vitamin E"], correct: 0, lang: "en" },
                        { q: "Normal blood pH range is:", options: ["7.35 - 7.45", "7.00 - 7.15", "7.50 - 7.60", "6.80 - 7.00"], correct: 0, lang: "en" },
                        { q: "RBC count of $6.5 \\times 10^{12}/L$ is called:", options: ["Erythrocytosis", "Erythropenia", "Leukocytosis", "Leukopenia"], correct: 0, lang: "en" },
                        { q: "What ion is crucial for all stages of blood coagulation?", options: ["$Ca^{2+}$", "$Na^+$", "$K^+$", "$Mg^{2+}$"], correct: 0, lang: "en" },
                        { q: "The lifespan of a typical red blood cell is:", options: ["120 days", "30 days", "10 days", "1 year"], correct: 0, lang: "en" },
                        { q: "Agglutinin 'beta' is found in the plasma of which group?", options: ["I(0) and II(A)", "III(B) and IV(AB)", "Only IV(AB)", "Only I(0)"], correct: 0, lang: "en" },
                        { q: "Agglutinogen 'B' is found on RBCs of which groups?", options: ["III(B) and IV(AB)", "I(0) and II(A)", "Only III(B)", "Only II(A)"], correct: 0, lang: "en" },
                        { q: "Serum differs from plasma by the absence of:", options: ["Fibrinogen", "Albumins", "Globulins", "Calcium"], correct: 0, lang: "en" },
                        { q: "Bilirubin is a metabolic product of which molecule?", options: ["Hemoglobin", "Albumin", "Cholesterol", "Glucose"], correct: 0, lang: "en" }
                    ]
                },
                {
                    id: "ps-3",
                    title: "Cardiovascular & Respiratory Systems",
                    content: `<div class="krok-marker">Focus:</div><p>ECG analysis, cardiac cycle, and lung volumes.</p>`,
                    questions: [
                        { q: "A 60-year-old man's ECG shows P-Q interval of 0.3s. Where is the conduction delay?", options: ["Atrioventricular node", "Sinoatrial node", "Purkinje fibers", "Left bundle branch"], correct: 0, lang: "en" },
                        { q: "Newborn born at 30 weeks has difficulty breathing. X-ray shows atelectasis. Cause?", options: ["Surfactant deficiency", "Mucus", "Fluid", "Fibrin"], correct: 0, lang: "en" },
                        { q: "Heart rate of 50 bpm (bradycardia) in a resting patient. Which nerve tone is high?", options: ["Vagus nerve", "Sympathetic", "Phrenic", "Glossopharyngeal"], correct: 0, lang: "en" },
                        { q: "Pleural wound causes intrapleural pressure to equal atmospheric. Condition?", options: ["Pneumothorax", "Hydrothorax", "Hemothorax", "Atelectasis"], correct: 0, lang: "en" },
                        { q: "Cardiac output 5 L/min and HR 70 bpm. Stroke volume is about:", options: ["71 ml", "100 ml", "50 ml", "150 ml"], correct: 0, lang: "en" },
                        { q: "High altitude (5000m) causes rapid breathing. Stimulus?", options: ["Decreased $PaO_2$", "Increased $CO_2$", "Decreased pH", "Cold"], correct: 0, lang: "en" },
                        { q: "ECG shows missing P waves, normal QRS at 40 bpm. Pacemaker?", options: ["Atrioventricular node", "Sinoatrial node", "Bundle of His", "Atrial pathways"], correct: 0, lang: "en" },
                        { q: "Which ECG wave shows ventricular repolarization?", options: ["T wave", "P wave", "QRS complex", "U wave"], correct: 0, lang: "en" },
                        { q: "Second heart sound (S2) is caused by the closure of:", options: ["Semilunar valves", "AV valves", "Mitral only", "Tricuspid only"], correct: 0, lang: "en" },
                        { q: "Calculate pulse pressure for BP 150/90 mmHg:", options: ["60 mmHg", "150", "90", "240"], correct: 0, lang: "en" },
                        { q: "Blood flow is slowest in which vessels?", options: ["Capillaries", "Aorta", "Arterioles", "Veins"], correct: 0, lang: "en" },
                        { q: "Total peripheral resistance is highest in:", options: ["Arterioles", "Capillaries", "Aorta", "Vena cava"], correct: 0, lang: "en" },
                        { q: "Which nerve increases the force and rate of heart contractions?", options: ["Sympathetic", "Vagus", "Phrenic", "Intercostal"], correct: 0, lang: "en" },
                        { q: "Surfactant is produced by which cells?", options: ["Type II pneumocytes", "Type I pneumocytes", "Alveolar macrophages", "Goblet cells"], correct: 0, lang: "en" },
                        { q: "Vital Capacity (VC) is the sum of:", options: ["TV + IRV + ERV", "TV + RV", "IRV + RV", "ERV + RV"], correct: 0, lang: "en" },
                        { q: "Frank-Starling law: force of contraction depends on:", options: ["Initial muscle stretch", "Heart rate", "Vagus tone", "Oxygen level"], correct: 0, lang: "en" },
                        { q: "The P-Q interval on an ECG represents:", options: ["Atrioventricular conduction", "Atrial depolarization", "Ventricular depolarization", "Ventricular repolarization"], correct: 0, lang: "en" },
                        { q: "Where is the respiratory center located?", options: ["Medulla oblongata", "Hypothalamus", "Thalamus", "Cerebellum"], correct: 0, lang: "en" },
                        { q: "Inspiratory muscles include the diaphragm and:", options: ["External intercostals", "Internal intercostals", "Rectus abdominis", "Obliques"], correct: 0, lang: "en" },
                        { q: "The first heart sound (S1) is caused by the closure of:", options: ["AV valves", "Semilunar valves", "Aortic valve", "Pulmonary valve"], correct: 0, lang: "en" },
                        { q: "Atropine increases heart rate by blocking:", options: ["M-cholinergic receptors", "N-cholinergic receptors", "Alpha-adrenergic", "Beta-adrenergic"], correct: 0, lang: "en" },
                        { q: "The volume of air left in lungs after maximal expiration is:", options: ["Residual volume", "Tidal volume", "Vital capacity", "Dead space"], correct: 0, lang: "en" },
                        { q: "How does an increase in $CO_2$ affect the respiratory rate?", options: ["Increases rate", "Decreases rate", "No effect", "Causes apnea"], correct: 0, lang: "en" },
                        { q: "Where is the pacemaker of a healthy heart located?", options: ["Sinoatrial node", "AV node", "Purkinje fibers", "Left atrium"], correct: 0, lang: "en" },
                        { q: "The QRS complex corresponds to:", options: ["Ventricular depolarization", "Atrial depolarization", "Ventricular repolarization", "Atrial repolarization"], correct: 0, lang: "en" },
                        { q: "What prevents alveoli from collapsing?", options: ["Surfactant", "Negative pressure", "Nitrogen", "Mucus"], correct: 0, lang: "en" },
                        { q: "A patient's systolic BP is 120 and diastolic is 80. Mean arterial pressure is about:", options: ["93 mmHg", "100", "40", "120"], correct: 0, lang: "en" },
                        { q: "During exercise, the increase in ventilation is primarily due to:", options: ["Proprioceptor activation", "Low O2", "High pH", "Low CO2"], correct: 0, lang: "en" },
                        { q: "An increase in vagus nerve activity will:", options: ["Decrease heart rate", "Increase heart rate", "Increase BP", "Decrease resistance"], correct: 0, lang: "en" },
                        { q: "Dead space air is located in:", options: ["Conducting airways", "Alveoli", "Pleural cavity", "Blood"], correct: 0, lang: "en" }
                    ]
                },
                {
                    id: "ps-4",
                    title: "Digestion & Excretion Physiology",
                    content: `<div class="krok-marker">Focus:</div><p>Enzymes, kidney filtration, and GI hormones.</p>`,
                    questions: [
                        { q: "Patient with steatorrhea (fatty stools). Deficiency of which enzyme?", options: ["Pancreatic Lipase", "Amylase", "Trypsin", "Pepsin"], correct: 0, lang: "en" },
                        { q: "Hormone stimulating gallbladder contraction in response to fat?", options: ["Cholecystokinin (CCK)", "Gastrin", "Secretin", "Insulin"], correct: 0, lang: "en" },
                        { q: "Glycosuria at normal blood glucose (4.5 mmol/L). Defect location?", options: ["Proximal tubule", "Glomerulus", "Distal tubule", "Loop of Henle"], correct: 0, lang: "en" },
                        { q: "High Renin levels in a hypertensive patient. Source cells?", options: ["Juxtaglomerular cells", "Podocytes", "Loop of Henle", "Proximal tubule"], correct: 0, lang: "en" },
                        { q: "Edema and proteinuria. Damage to which renal structure?", options: ["Glomerular filter", "Proximal tubule", "Collecting duct", "Ureter"], correct: 0, lang: "en" },
                        { q: "Gastrectomy patient cannot absorb $B_{12}$. Missing cells?", options: ["Parietal cells", "Chief cells", "G-cells", "Mucous cells"], correct: 0, lang: "en" },
                        { q: "Secretin production inhibited. Decrease in pancreatic juice rich in:", options: ["Bicarbonates", "Enzymes", "Mucus", "Bile"], correct: 0, lang: "en" },
                        { q: "BP 80/50 and oliguria after blood loss. Cause?", options: ["Decreased filtration pressure", "Increased reabsorption", "ADH block", "Kidney stone"], correct: 0, lang: "en" },
                        { q: "Severe diarrhea and metabolic acidosis. Loss of what?", options: ["Bicarbonates", "Chlorides", "HCl", "Potassium"], correct: 0, lang: "en" },
                        { q: "Salt intake increase. Hormone for water reabsorption?", options: ["Vasopressin (ADH)", "Aldosterone", "Insulin", "ANP"], correct: 0, lang: "en" },
                        { q: "Bile is primarily needed for:", options: ["Fat emulsification", "Protein breakdown", "Starch breakdown", "HCl neutralization"], correct: 0, lang: "en" },
                        { q: "Trypsinogen is activated by:", options: ["Enterokinase", "Bile", "HCl", "Pepsin"], correct: 0, lang: "en" },
                        { q: "What cells in the stomach secrete HCl?", options: ["Parietal cells", "Chief cells", "Mucous cells", "G-cells"], correct: 0, lang: "en" },
                        { q: "Where does the majority of water reabsorption occur in the kidney?", options: ["Proximal tubule", "Distal tubule", "Loop of Henle", "Collecting duct"], correct: 0, lang: "en" },
                        { q: "Glomerular Filtration Rate (GFR) is normally around:", options: ["125 ml/min", "500 ml/min", "10 ml/min", "1 L/min"], correct: 0, lang: "en" },
                        { q: "Specific Dynamic Action (SDA) is highest for:", options: ["Proteins", "Fats", "Carbohydrates", "Vitamins"], correct: 0, lang: "en" },
                        { q: "At what BP does renal filtration stop?", options: ["< 70 mmHg", "120 mmHg", "100 mmHg", "150 mmHg"], correct: 0, lang: "en" },
                        { q: "Aldosterone increases the reabsorption of:", options: ["$Na^+$", "$K^+$", "$Ca^{2+}$", "$Mg^{2+}$"], correct: 0, lang: "en" },
                        { q: "What stimulates the release of Secretin?", options: ["HCl in the duodenum", "Fats in the duodenum", "Amino acids", "Glucose"], correct: 0, lang: "en" },
                        { q: "The specific enzyme that digests starch in the mouth is:", options: ["Amylase (Ptyalin)", "Pepsin", "Lipase", "Trypsin"], correct: 0, lang: "en" },
                        { q: "Glucose is reabsorbed in the proximal tubule via:", options: ["Secondary active transport", "Simple diffusion", "Facilitated diffusion", "Osmosis"], correct: 0, lang: "en" },
                        { q: "Center of hunger is located in:", options: ["Lateral hypothalamus", "Ventromedial hypothalamus", "Thalamus", "Medulla"], correct: 0, lang: "en" },
                        { q: "Center of satiety is located in:", options: ["Ventromedial hypothalamus", "Lateral hypothalamus", "Thalamus", "Medulla"], correct: 0, lang: "en" },
                        { q: "Bile pigments (like bilirubin) are formed from:", options: ["Heme", "Globin", "Cholesterol", "Fatty acids"], correct: 0, lang: "en" },
                        { q: "Main function of the large intestine:", options: ["Water absorption", "Protein digestion", "Fat digestion", "HCl secretion"], correct: 0, lang: "en" },
                        { q: "What activates pepsinogen?", options: ["HCl", "Enterokinase", "Bile", "Gastrin"], correct: 0, lang: "en" },
                        { q: "Inulin clearance is used to measure:", options: ["GFR", "Renal blood flow", "Tubular secretion", "Glucose threshold"], correct: 0, lang: "en" },
                        { q: "What happens during 'Defecation reflex'?", options: ["Internal sphincter relaxes", "External sphincter contracts", "Peristalsis stops", "BP drops"], correct: 0, lang: "en" },
                        { q: "Gastrin is secreted by:", options: ["G-cells", "Chief cells", "Parietal cells", "S-cells"], correct: 0, lang: "en" },
                        { q: "The enzyme that digests milk protein in infants is:", options: ["Rennin", "Pepsin", "Amylase", "Lipase"], correct: 0, lang: "en" }
                    ]
                },
                {
                    id: "ps-5",
                    title: "Endocrine, CNS & Sensory Systems",
                    content: `<div class="krok-marker">Focus:</div><p>Hormonal diseases, brain areas, and reflexes.</p>`,
                    questions: [
                        { q: "35-year-old woman with tremors, weight loss, heat intolerance. Hormone?", options: ["Thyroxine (T4)", "Insulin", "Aldosterone", "Growth hormone"], correct: 0, lang: "en" },
                        { q: "Calm, persistent, slow, stable emotions. Temperament?", options: ["Phlegmatic", "Sanguine", "Choleric", "Melancholic"], correct: 0, lang: "en" },
                        { q: "Unsteady gait, tremors, muscle hypotonia (ataxia). Damage?", options: ["Cerebellum", "Hypothalamus", "Thalamus", "Basal ganglia"], correct: 0, lang: "en" },
                        { q: "Adult with large nose, jaw, and hands. Overproducing gland?", options: ["Anterior pituitary (GH)", "Thyroid", "Adrenal cortex", "Pancreas"], correct: 0, lang: "en" },
                        { q: "Bronze skin, weakness, low BP. Diagnosis?", options: ["Addison's disease", "Cushing's syndrome", "Diabetes", "Acromegaly"], correct: 0, lang: "en" },
                        { q: "Night blindness (nyctalopia) deficiency?", options: ["Rhodopsin (Vitamin A)", "Iodopsin", "Melanin", "Vitamin K"], correct: 0, lang: "en" },
                        { q: "Motor speech disorder (Broca's aphasia). Location?", options: ["Left frontal lobe", "Right temporal lobe", "Occipital lobe", "Parietal lobe"], correct: 0, lang: "en" },
                        { q: "Diabetes insipidus (polyuria, low specific gravity). Cause?", options: ["ADH deficiency", "Insulin deficiency", "Aldosterone excess", "Glucagon excess"], correct: 0, lang: "en" },
                        { q: "Astereognosis (cannot recognize objects by touch). Damaged lobe?", options: ["Parietal lobe", "Frontal lobe", "Occipital lobe", "Temporal lobe"], correct: 0, lang: "en" },
                        { q: "Fight-or-flight response gland?", options: ["Adrenal medulla", "Adrenal cortex", "Thyroid", "Parathyroid"], correct: 0, lang: "en" },
                        { q: "Which hormone lowers blood calcium levels?", options: ["Calcitonin", "PTH", "Thyroxine", "Cortisol"], correct: 0, lang: "en" },
                        { q: "Which hormone raises blood calcium levels?", options: ["PTH", "Calcitonin", "Insulin", "Aldosterone"], correct: 0, lang: "en" },
                        { q: "The 'Master Gland' that controls other glands is:", options: ["Pituitary", "Thyroid", "Adrenal", "Thalamus"], correct: 0, lang: "en" },
                        { q: "Wernicke's area is responsible for:", options: ["Understanding speech", "Producing speech", "Vision", "Balance"], correct: 0, lang: "en" },
                        { q: "Occipital lobe is primarily for:", options: ["Vision", "Hearing", "Smell", "Motor control"], correct: 0, lang: "en" },
                        { q: "Temporal lobe is primarily for:", options: ["Hearing", "Vision", "Taste", "Touch"], correct: 0, lang: "en" },
                        { q: "Babinski reflex in an adult is a sign of:", options: ["Upper motor neuron lesion", "Normal health", "Lower motor neuron lesion", "Sensory loss"], correct: 0, lang: "en" },
                        { q: "Excessive cortisol causes:", options: ["Cushing's syndrome", "Addison's disease", "Acromegaly", "Diabetes insipidus"], correct: 0, lang: "en" },
                        { q: "Which cells in the retina are for color vision?", options: ["Cones", "Rods", "Bipolar cells", "Ganglion cells"], correct: 0, lang: "en" },
                        { q: "Hypothalamus regulates body temperature and:", options: ["Thirst and Hunger", "Coordination", "Vision", "Speech"], correct: 0, lang: "en" },
                        { q: "The 'stress hormone' released by the adrenal cortex is:", options: ["Cortisol", "Insulin", "Oxytocin", "Melatonin"], correct: 0, lang: "en" },
                        { q: "Oxytocin is produced by the:", options: ["Hypothalamus", "Anterior Pituitary", "Thyroid", "Ovaries"], correct: 0, lang: "en" },
                        { q: "What is the result of Cerebellum damage?", options: ["Asynergy and Ataxia", "Paralysis", "Blindness", "Deafness"], correct: 0, lang: "en" },
                        { q: "Which temperament is Strong, Unbalanced, and Excitable?", options: ["Choleric", "Sanguine", "Phlegmatic", "Melancholic"], correct: 0, lang: "en" },
                        { q: "Where is the primary motor cortex?", options: ["Precentral gyrus", "Postcentral gyrus", "Temporal lobe", "Occipital lobe"], correct: 0, lang: "en" },
                        { q: "Myxedema (hypothyroidism) in adults causes:", options: ["Sluggishness and weight gain", "Weight loss", "Exophthalmos", "Tachycardia"], correct: 0, lang: "en" },
                        { q: "Which receptor senses muscle stretch?", options: ["Muscle spindle", "Golgi tendon organ", "Pacinian corpuscle", "Nociceptor"], correct: 0, lang: "en" },
                        { q: "The primary function of the Eustachian tube is:", options: ["Equalize pressure", "Hearing", "Balance", "Sound amplification"], correct: 0, lang: "en" },
                        { q: "Melatonin is secreted by the:", options: ["Pineal gland", "Pituitary", "Thyroid", "Thymus"], correct: 0, lang: "en" },
                        { q: "The 'blind spot' in the eye is where:", options: ["Optic nerve leaves the eye", "Macula is located", "Lens is attached", "Rods are most dense"], correct: 0, lang: "en" }
                    ]
                }
            ]
        },
        { id: "pharma", title: "Фармакологія", en: "Pharmacology", topics: [] },
        { id: "pathmorph", title: "Патоморфологія", en: "Pathomorphology", topics: [] },
        { id: "pathphys", title: "Патофізіологія", en: "Pathophysiology", topics: [] },
        { id: "anatomy", title: "Анатомія", en: "Anatomy", topics: [] },
        { id: "histo", title: "Гістологія", en: "Histology", topics: [] }
    ]
};
